/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchIdRouteImport } from './routes/match.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/feed'
    | '/login'
    | '/matches'
    | '/profile'
    | '/signup'
    | '/match/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/feed'
    | '/login'
    | '/matches'
    | '/profile'
    | '/signup'
    | '/match/$id'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/feed'
    | '/login'
    | '/matches'
    | '/profile'
    | '/signup'
    | '/match/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  MatchIdRoute: typeof MatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  MatchIdRoute: MatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
