# Generated by Django 6.0.5 on 2026-06-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partida",
            name="local",
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name="participacao",
            name="partida",
        ),
        migrations.RemoveField(
            model_name="participacao",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="partida",
            name="criador",
        ),
        migrations.AddField(
            model_name="partida",
            name="cidade",
            field=models.CharField(default="Rio de Janeiro", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="partida",
            name="status",
            field=models.CharField(default="Aberta", max_length=30),
        ),
        migrations.DeleteModel(
            name="Local",
        ),
        migrations.DeleteModel(
            name="Participacao",
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
